// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvnmazbbosukwbbuwjus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2bm1hemJib3N1a3diYnV3anVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA1NTQzOTYsImV4cCI6MjA1NjEzMDM5Nn0.uICYwkO4BW-z7xSXzJVOSI3rV8laXNi9LsemKbKRPbQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);